elastic:
  image: elasticsearch:2.1.1
  volumes:
    - ./esdata:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
  command: -Des.network.bind_host=0.0.0.0
logstash:
  image: logstash:2.1.1
  ports:
    - "5043:5043"
  volumes:
    - ./logstash/conf.d:/etc/logstash/conf.d:ro
    - ./certs:/etc/ssl:ro
  net: "host"
  command: logstash -f /etc/logstash/conf.d
kibana:
  image: kibana:4.3.1
  ports:
    - "5601:5601"
  net: "host"
  environment:
    - ELASTICSEARCH_URL=http://localhost:9200
apache_sample:
  image: eboraas/apache
  volumes:
    - ./log/apache:/var/log/apache2
  ports:
    - "8080:80"
    - "8443:443"
logstash-forwarder:
  build: ./logstash-forwarder
  volumes:
    - ./logstash-forwarder/sample_config:/etc/logstash-forwarder/conf.d:ro
    - ./certs:/var/certs:ro
    - ./log/apache:/var/log/apache-server:ro
  net: "host"
  command: /etc/logstash-forwarder/conf.d/logstash-forward-config.json