version: '3.0'

services:
    activemq:
        build: .
        image: wurstmeister/kafka
        # restart: always
        container_name: kafka
        ports:
            - "8161:8161"
            - "61616:61616"

networks:
    default:
        external:
            name: mynet

