##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8080

###################  spring配置  ###################
spring:
  profiles:
    active: dev
debug: true

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev



